function [otime,lon,lat,dep,M,M0,Mw,eid] = read_mech_table(filename)
%READ_MECH_TABLE read moment tensor table generated by write_mech_table.m
%
% INPUT
%   filename    filename (printed from write_mech_table.m)
%
% OUTPUT
%   otime       n x 1 origin time (Matlab format)
%   lon         n x 1 longitude
%   lat         n x 1 latitude
%   dep         n x 1 depth, in km
%   M           6 x n array of moment tensors in GCMT convention (up-south-east)
%                   M = [Mrr Mtt Mpp Mrt Mrp Mtp], units N-m
%   eid         n x 1 event IDs (may be empty)
%
% If you want to calculate strike, dip, rake, M0, Mw, see CMT2TT.m
%
% Carl Tape, 7/16/2015
%

% get the number of header lines
[status,cmdout] = system(sprintf('grep -n COLUMNS %s | cut -f1 -d:',filename));
NHEADER = str2num(cmdout) + 2;

fid = fopen(filename);
if NHEADER==22
    disp('read_mech_table.m: normal format');
    C = textscan(fid,'%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s','headerlines',NHEADER);
else
    disp('read_mech_table.m: extended format');
    C = textscan(fid,'%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%s','headerlines',NHEADER);
end
fclose(fid);
otime = datenum(C{1},C{2},C{3},C{4},C{5},C{6});
% check: datestr(otime,'yyyy-mm-dd HH:MM:SS.FFF')
lon = C{7};
lat = C{8};
dep = C{9};
% the Mij values are listed with the highest precision
% (this is why we return M but not strike, dip, rake, M0, Mw, gamma, delta, etc)
M = [C{10} C{11} C{12} C{13} C{14} C{15}]';
eid = C{23};

[Mw,M0] = CMT2mw(M);

%==========================================================================
% EXAMPLES (these will only work with GEOTOOLS at UAF)

if 0==1
    % Vipul catalog for Tape2015 paper
    [otime,lon,lat,dep,M,M0,Mw,eid] = read_mech_table('/home/carltape/tu_test_mech_extended.txt');
    
    display_eq_summary(otime,lon,lat,dep,Mw);

    % base directory
    bdir = [getenv('REPOS') '/manuscripts/'];

    % Vipul catalog for Tape2015 paper
    idir = [bdir 'carltape/mfsz/data/'];
    [otime,lon,lat,dep,M,M0,Mw,eid] = read_mech_table('GCMT_mffz_mech.txt');
    [gamma,delta,M0,kappa,theta,sigma,K,N,S,thetadc,lam,U] = CMT2TT(M);
    display_eq_summary(otime,lon,lat,dep,Mw);
    
    % Vipul catalog for Silwal2016 paper
    idir = [bdir 'vipul/papers/2014mt/data/'];
    [otime,lon,lat,dep,M,M0,Mw,eid] = read_mech_table([idir 'SCAK_mech.txt']);
    display_eq_summary(otime,lon,lat,dep,Mw);
    
    % Celso catalog for Alvizuri2016 paper
    idir = [bdir 'alvizuri/papers/2014fmt/data/'];
    [otime,lon,lat,dep,M,M0,Mw,eid] = read_mech_table([idir 'uturuncu_mech.txt']);
    display_eq_summary(otime,lon,lat,dep,Mw);
end

%==========================================================================
